### PR TITLE
Consistent support for isRequired across all field types.

### LINKED ISSUE #1245: isRequired has no effect
``` js
  fields: {
   description: {
     type: Text,
     isRequired: true
   }
  }
```

Expectation is that it fails if `null` (or `''`, aka empty string) in the administration UI on creation.

Actuality: It creates an item without an error.

**edit:** Unclear if this is meant be enforced by GraphQL,  but,  I can verify that you can `create*` `isRequired` fields as `null` without error too.  `isUnique` **is** enforced by GraphQL.

### PR DESCRIPTION
**Pull request by timleslie**
Fixes #1245

Add a check during for the `_validateInput` phase for non-relationship fields which have `isRequired` set but have not supplied/supplied a null value.

### CODE REVIEW

File: packages/keystone/lib/List/index.js [hunk 1]
```diff
@@ -1094,6 +1094,24 @@ module.exports = class List {
       originalInput,
       actions: mapKeys(this.hooksActions, hook => hook(context)),
     };
+
+    // Check for isRequired
+    const fieldValidationErrors = this.fields
```
Comment (jesstelford) [inline packages/keystone/lib/List/index.js]: This happens _after_ relationships are resolved: https://github.com/keystonejs/keystone-5/blob/16386a2d96e0378e2e2a433c8de3bbce21745515/packages/keystone/lib/List/index.js#L1280

This could result in a related item being created or deleted before the input is validated (and then fails validation)

File: packages/keystone/lib/List/index.js [hunk 2]
```diff
@@ -1094,6 +1094,24 @@ module.exports = class List {
...
+      .filter(
+        f =>
+          f.isRequired &&
+          !f.isRelationship &&
+          (resolvedData[f.path] === undefined || resolvedData[f.path] === null)
```
Comment (jesstelford) [inline packages/keystone/lib/List/index.js]: Can we rename `f` -> `field`?

File: packages/keystone/lib/List/index.js [hunk 3]
```diff
@@ -1094,6 +1094,24 @@ module.exports = class List {
       originalInput,
       actions: mapKeys(this.hooksActions, hook => hook(context)),
     };
+
+    // Check for isRequired
+    const fieldValidationErrors = this.fields
+      .filter(
+        f =>
+          f.isRequired &&
+          !f.isRelationship &&
```
Comment (jesstelford) [inline packages/keystone/lib/List/index.js]: When is an `isRequired` relationship validated?

Comment (timleslie) [reply packages/keystone/lib/List/index.js]: Never :-) Need to create a separate issue for that, because as you noted above, we attempt to resolve relationships before the validation step.

Comment (jesstelford) [reply packages/keystone/lib/List/index.js]: Got it 👍

**Comment by timleslie** [comment]
Note: This PR does not address `isRequired` on `Relationship` fields. As noted in the review comments above, the relationship value is used before the validation step in the lifecycle, and so needs to be handled separately. This is captured in issue #719.
